### ISSUE TITLE
Different behaviour Chrome and Firefox when using prop('selectedIndex',-1)

### ISSUE THREAD

**Issue by invasionofsmallcubes** [thoughtbot/backbone-support#22]
It's the first time I use backbone-support to handle zombie views.
Before introducing it, I did not have the following problem:

        this.$el.append(this.template());
    
        // this view fills up a select with options taken from a web services
        this.renderChildInto(new App.view.ResourcesView({name: "idActivityDesc", url: "/wfc-services/resources/activities"}), "#divIdActivityDesc");
    
        // population of the forms elements according to the loaded model
        this.populateSelectElements();
        this.populateTextElements();
    
        if(this.model.get('completed')) {
            this.$("#active").removeAttr("disabled");
        }
    
        this.delegateEvents(this.events);
        return this;

With Firefox it's all working fine. If the model is empty the `select` elements are going to be set up with default elements. In my case is **selectedIndex** to **-1**.

Going in debug inside the view everything seems fine. I have the problem when the view is going to be happened to the parent via the method `renderChildInto`. The dom is fine, but without the changes derived from the `populateSelectElements()` if the model is empty. If it's not empty I have no problem and the view is working fine.

I'm really puzzled about it because before the `return this;` statement, even in Chrome/Chromium I see the **selectedIndex** to **-1**. But in the final rendered view on the browser I see the select having **selectedIndex** to **0**.

In the composite_view.js the called code is:

      renderChild: function(view) {
        view.render();
        this.children.push(view);
        view.parent = this;
      },
      
      renderChildInto: function(view, container) {
        this.renderChild(view);
        this.$(container).html(view.el);
      },

**Comment by ecbypi** [comment]
@invasionofsmallcubes Are you still experiencing this problem?  Were you able to find a solution?  If not, could you provide a gist or sample code that reproduces the problem?

**Comment by invasionofsmallcubes** [comment]
@ecbypi I honestly cannot tell you, it has been ages. I'm not using backbone anymore.

**Comment by ecbypi** [comment]
OK. Thanks for following up.
