### ISSUE TITLE
Deprecation warning - unbindFromAll

### ISSUE THREAD

**Issue by kelvinst** [thoughtbot/backbone-support#28]
Seems like in 0.5.0 the CompositeView is calling `unbindFromAll` on `leave`. The new correct behavior is to call `stopListening`.

**Comment by kelvinst** [comment]
I think [this commit](https://github.com/thoughtbot/backbone-support/commit/99ecf853c4cb9854fdc4ca66c135173ae71dcd27) resolves the problem right? There are plans to release a `0.5.1`?

**Comment by ecbypi** [comment]
@kelvinst, apologies for the trouble / delay.  I just cut `v0.5.1`.

**Comment by kelvinst** [comment]
It's ok... Waiting for it! 

And thanks for the "flash response". :grin:

**Comment by kelvinst** [comment]
Updated to `0.5.1` here... Problem SOLVED sir! Really thanks!
