### ISSUE TITLE
The page needs to be reload to access new model data in composite view

### ISSUE THREAD

**Issue by AjayBarot** [thoughtbot/backbone-support#29]
Hi all,
      In my project we have a situation where page must reload to access latest model data in composite view. Let me show the code below code is written in coffeescript : 
[gist link](https://gist.github.com/AjayBarot-BTC/8fd820af89b0bf4d7818)
Please can any one explain me why reload problem occurs ?
Thank you & regards
Ajay Barot

**Comment by ecbypi** [comment]
Hi @AjayBarot-BTC, I'm not immediately aware why this would be an issue with `CompositeView` or `Backbone.View`.  Could you provide more context as to how you're reloading model data within a `CompositeView` or what method fails such that you have to reload the page?  The gist you provided isn't super helpful since it's a lot of code to grok and I can't immediately separate domain logic from behavior.

**Comment by AjayBarot** [comment]
@ecbypi Thanks for a quick reply . 
Let me explain the problem in detail
**router**
({
  editItem: function(itemId) {
    var assetView, item;
    item = this.homeMenu.getItem(itemId);
    assetView = ActivityView.create(item.get("activity_type"), {
      groups: this.groups,
      people: this.people
    });
    return this.swap(new EditItemView({
      model: item,
      activityView: assetView,
      roles: this.roles,
      tags: this.tags,
      globalStockImages: this.globalStockImages,
      groups: this.groups
    }));
  }
});

activity_view 
this.ActivityView = new PolymorphicFactory("activity view");

[polymorphicFactory](https://gist.github.com/AjayBarot-BTC/92a0a6747cd705a3704b)

[edit_item_view](https://gist.github.com/AjayBarot-BTC/31241d0960b1e731f9df)

Now in item_form asset activity view called by this function 
({
  renderActivityView: function() {
    this.activityView.model = this.model.activity;
    this.renderChild(this.activityView);
    this.activityView.bind("loading", this.loading, this);
    this.activityView.bind("change", this.changeActivity, this);
    return this.$(".activity_fields").append(this.activityView.el);
  }
});
and submit saved functions are triggered from here

Now in content/activity_view/asset.js
Here I show two check box and configure link as given in image 
![link](https://cloud.githubusercontent.com/assets/5164950/7686921/14f8d72a-fdb7-11e4-9581-fb753e8bd988.png)
here I am saving model data by using serialize method : 
({
  serialize: function() {
    return $.extend(this.attributes, {
      base_module_ids: this.$('#base_module_ids').val()
    });
  }
});
Here is my as_json method in model asset.rb
`if base_modules`
`modules_array = []`
`base_modules.each do |base_module|`
`modules = {}`
`modules[:base_module_id] = base_module.id`
`modules[:modulable_type] = base_module.modulable_type`
`modules_array << modules` `end`
`result[:base_module_ids] = modules_array`
`end` `result`

everything is working expect update base_module  scenario
Following is the this.model log after save 

![log](https://cloud.githubusercontent.com/assets/5164950/7687147/ca1cd416-fdb8-11e4-8c7c-fa7d72c1f77e.png)

After reload (refresh window) base_module_ids shown as a object
Following is the this.model log after refresh window

![log2](https://cloud.githubusercontent.com/assets/5164950/7687268/aac8b944-fdb9-11e4-96e8-c488455d91cd.png)
By reload page we can solved this issue but its taking too much time to reload page in production so we have to improve this. 

We are using backbone-on-rails (1.0.0.0) and backbone-support (0.4.0)

You can see whole asset.js (content/activity_view/asset.js) for reference 
[asset.js](https://gist.github.com/AjayBarot-BTC/389a3d6fc6c72d278497)

Please tell me if you don't get anything from above code or anything.
Thanks for your support

Thanks & Regards
Ajay Barot

**Comment by ecbypi** [comment]
Hi @AjayBarot-BTC, the additional code doesn't help me see why `CompositeView` would prevent `Model#sync()`, `Model#fetch()` or any other means of updating a model or collection from behaving correctly.

Could you provide a simplified, reproducible example of the problem independent of the business logic of your app?
